development:
  adapter: postgresql
  encoding: utf8
  database: joelsmobile_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: joelsmobile_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: joelsmobile_production
  pool: 5
  host: localhost
